version: "3"
services:
    nodeserver:
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "3000:80"